// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CodemirrorController from "./codemirror_controller"
application.register("codemirror", CodemirrorController)

import OpenZaidController from "./open_zaid_controller"
application.register("open-zaid", OpenZaidController)

import RunZaidController from "./run_zaid_controller"
application.register("run-zaid", RunZaidController)

import SaveZaidController from "./save_zaid_controller"
application.register("save-zaid", SaveZaidController)

import ZaidExamplesController from "./zaid_examples_controller"
application.register("zaid-examples", ZaidExamplesController)
